### ISSUE TITLE
No such module 'Deferred'

### ISSUE THREAD

**Issue by jwwilson** [mozilla/firefox-ios#2080]
I have installed the project as the instruction,but there is an error。No such module 'Deferred'。How  can I resolve it ?

**Comment by iosbin** [comment]
me too.

**Comment by lucas1993ch** [comment]
me too.

**Comment by AaronMT** [comment]
@farhanpatel @sleroux any ideas?

**Comment by sleroux** [comment]
Usually this error indicates the dependencies were not downloaded since the `Deferred` framework is one of the first ones that's linked in from Carthage. 

1. Double check to see that you ran `./bootstrap` from the root of the project.
2. Currently the codebase only works on Xcode 7. If you've used Carthage with Xcode 8 in the past you may need to switch your xcode build tools to point to the Xcode 7 toolchain instead using `xcode-select -s /path/to/xcode7`

**Comment by ServusJon** [comment]
Having the same problem with xcode 8 :-(

**Comment by farhanpatel** [comment]
The project isn't updated yet for xcode8. We have a few more things left in our swift 2.3 branch https://github.com/mozilla/firefox-ios/pull/1942

**Comment by farhanpatel** [comment]
This is fixed now. The project compiles with swift 2.3 and should work. Make sure to delete your existing Carthage folder before building again. 

I'll close this issue for now. If the issue does come up again feel free to reopen. 😄

**Comment by knighthb** [comment]
This problem is still comes to me , I both tried with xcode8 and xcode7 followed by your instruction, but it doesn't work

**Comment by AaronMT** [comment]
We only support Xcode 8 now. Have you tried re-cloning the project and running `./boostrap.sh` to fetch all dependencies?

**Comment by LIZUBA** [comment]
I have the same problem too and I have run sh ./bootstrap.sh

**Comment by Hanwp** [comment]
I tried run sh ./bootstrap.sh
```
bogon:firefox-ios xxx$ sh ./bootstrap.sh 
./bootstrap.sh: line 32: carthage: command not found
cp: Carthage/Cartfile.resolved: No such file or directory
```

**Comment by JohnJGL** [comment]
@Hanwp It's because you haven't install Carthage, try 'brew Install Carthage' in you terminal.
